# Generated by Django 5.0.14 on 2025-05-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoriaproducto_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='accesorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.accesorio'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
