# Generated by Django 5.0.14 on 2025-05-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_itemcarrito_accesorio_alter_itemcarrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='accesorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.accesorio'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
    ]
